// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShowPetsController from "./show_pets_controller"
application.register("show-pets", ShowPetsController)

import TypedController from "./typed_controller"
application.register("typed", TypedController)
